### ISSUE TITLE
Writing Resources

### ISSUE THREAD

**Issue by taylorcate** [taylorcate/MUDDLE#15]
Hello MUDDLERS!

I was perusing the wonderful land of GitHub and I came across some interesting composition resources I thought you might enjoy! Let me know which are your favorites and, _please_, document your process! Always nice to give members of the GitHub community some traction on their hard work. :hammer:

[ZenPen](http://zenpen.io/)
Created by @tholman
This application allows you to compose, invert (for less strained visibility), set a target word count, and save your textual work, then download it as Markdown, HTML, or Plain Text. I found writing in this application to be a very enjoyable experience. :thumbsup:

[Nulis](https://nulis.io)
Created by @raymestalez
This is an open source tree editor for writers. It allows you to hierarchically organize information as trees. Who knows the creative potential for something like that! :evergreen_tree:

[funbook](https://funbook.js.org)
Created by @egoist
This is (to the best of my knowledge) a static website generator that is specifically designed for composing books or multi-chapter works. If anyone figures out how to get this up and running please let me know. :heart_eyes:

[Poet Assistant](https://github.com/caarmen/poet-assistant)
Created by @caarmen
This is a mobile app with a built-in dictionary, thesaurus, rhyming dictionary, composition window, and text-to-speech read back features. Fun mobile-poetry potential here for sure! :iphone:

[blackout](https://mkremins.github.io/blackout/)
Created by @mkremins
An auto-poem generator that blacks out web page text and leaves you with something to muse over. Very intriguing and certainly worth adding to your toolbar. :see_no_evil:

**Comment by nadinejl** [comment]
Wow, these are great! Thanks for sharing them! Some crazy smart people on Github. What a tribe. And what a stargazer is @taylorcate! All awful rhyming attempts aside....  the ones that first attracted me the most, according to the titles/descriptions were "blackout" (because I love blackout poetry) and "funbook" (because I'd like to make a book). After quickly trying them all, I thought ZenBook was best click here, for immediate UI (simple instructions for dummies like me, right in the hitpage! Sah-weet!). "Nullis" looked indeed the one I **should** look into further, seems like lots of potential there. Especially for pantsers like me to increase their plotting potential. Also I loved the name. "Funbook" was way beyond my abilities to grasp at this moment (tech n00b that I am). But I also loved that name and idea. Poetry Assistant I did not yet try (because I'm on desktop, and sometimes iOS). All very inspiring! ✨🙌 Thanks again! xoxo

**Comment by RJP43** [comment]
# Resources for Writing on GitHub (basics)

- [GitHub Guides: Mastering Markdown](https://guides.github.com/features/mastering-markdown/)
- [GitHub Help: Basic Writing and Formatting Syntax](https://help.github.com/articles/basic-writing-and-formatting-syntax/)
- @rxaviers [Complete List of GitHub Emoji Markdown](https://gist.github.com/rxaviers/7360908)
