### ISSUE TITLE
Help Sphinxy Catch Bugs !?! 

### ISSUE THREAD

**Issue by nadinejl** [taylorcate/MUDDLE#16]
# Call for Play link is dead maybe?
Hi @taylorcate @RJP43 
Not sure if this is the right place for this, feel free to delete or what have you :) But Just noticed that on the MUDDLE Wiki page, this link seems to leads to 404 error:

On this page: https://github.com/taylorcate/MUDDLE/wiki
"November 2nd, 2018 - [MUDDLE  #5  FOR PLAY]"(https://github.com/taylorcate/MUDDLE/blob/master/PromotionalMaterials/CFP_MM_11-2.png)
link appears dead. Just FYI :)

xoxo

**Comment by nadinejl** [comment]
p.s. I'm sorry I can't remember how to add labels! #mommybrain #oldbroad  And can't find your post telling me about how. #facepalm Arg. #process :)

**Comment by taylorcate** [comment]
You are so right, that link is dead. I'll patch it up today! Happens when we're constantly trying to organize our toys 😂 thank you for letting us know!

**Comment by RJP43** [comment]
@nadinejl #eagle{2}ye #bugcatcher -- Thanks, neighbor! :ant::bird: 

**As for the label inquiry,** #mommybrain or not if you were looking to label this issue you won't see the option to. O{I]n this main MUDDLE issues board][backyard only direct "contributors" (@taylorcate and I) can add labels. I will add the appropriate labels now. In the future and as we are formulating a workflow, an editor will add label(s) and assign a reviewer for "creator-created issues". Seriously tho, THANKS again for catching the bug and letting us know - this was the just right place to do so!! :heart_eyes: 

**Now in regards to labels [_...again_]**, since creators contribute in "forkfuls" we leave labels up to you in your backyard. In fact, while we [model|muddle] in our wiki, projects and issues boards, README.md files, repo. tags, and repo. description (:arrow_down:reference image:arrow_down:),  
![main MUDDLE repo description](https://user-images.githubusercontent.com/8645521/48679518-f8484200-eb56-11e8-9c7b-6d030e231acf.png)
we encourage creators to c{ustomize][reate all of the above on you][thei}r "muddled fork". As we continue to create the MUDDLE model we hope our methods get muddled by watching your muddle grow. :sunflower: 
 
:revolving_hearts:model turns to muddle while muddle turns to model:revolving_hearts: 

@nadinejl I am heading over to your backyard soon with an invite to play; meanwhile, I am renaming this issue and inviting other #eagle{2}ye #bugcatcher(s) to point out bugs here! Thanks again (a million times over) for contributing to the #neighBBoard and helping catch bugs!

**Comment by nadinejl** [comment]
@RJP43 I love this! Thank you! 🥇☺️👏👍💖
