### ISSUE TITLE
MUDDLER Introductions (2018-19 Season)

### ISSUE THREAD

**Issue by taylorcate** [taylorcate/MUDDLE#20]
Hello MUDDLERS! 

Now that we have a good number of neighbors in the sandbox, I'd love it if we could take a moment and introduce ourselves! If you could include **your preferred methods of composition (graphic art, digital art, poetry, fiction, video games, music, video, etc.), your experience with Git and GitHub, and where you're from** I think that would be a great start! Please also link to your existing MUDDLE contributions, any publicly hosted works, websites, blogs, or social media accounts so we can find you in the ether! :stars:

In case you want to follow MUDDLE: 
@muddle_mag (Insta and Twitter)
@muddlemag (Facebook)

Best, Tay

@nadinejl @gkthiruvathukal @backpacker396 @jksily @gmoe @JonHolt @snblickhan @tymonaghan

**Comment by taylorcate** [comment]
I'll start :blush:

My name is Taylor and I am MUDDLE's Content Editor! I graduated from Widener University in 2017 with my Bachelor's degree in English and I will graduating from Loyola University Chicago in May 2019 with my Master's degree in Textual Studies and Digital Humanities. My experience with Git and GitHub is fairly limited: I've only begun using it seriously for my own projects in the past year or so and MUDDLE is the first of these projects to have an ingrained, collaborative workflow.
I'm from the Pocono Mountains in woodsy Pennsylvania and I attribute much of my digital naivety to growing up on a mountain, but I wouldn't have traded it for the world. :sunrise_over_mountains: I love writing poetry, but my methods of creation are usually very slow going. I find that deadlines are very good for me, plus also having lots of people around to hold me accountable to working on my art. :sweat_smile: You can check out some of my graphic design projects, my poetry, and my blog at my [Pathbrite Digital Portfolio](https://pathbrite.com/taylorcate14/profile). 

I'm also on Instagram :) @adventscholar

**Comment by jksily** [comment]
My name is Josh. Alternatively, you can call me jks. It would feel weird being at a screen and not being called by my internet name. I graduated Widener University in 2017 with my Bachelor's in English (shout out to Taylor for putting up with my inconsistencies these past 4 & 1/2 years). I currently live in Wilmington, DE. 

I have minimal experience with Git and GitHub. I am a big proponent of open-source projects though, and am a general computer fiend. I wrote my senior thesis on video games. I'm hoping to learn and utilize Git more in the coming months as I want to contribute to more projects rather than just enjoy the benefits of their existence. 

I mainly work in fiction - short stories in particular. I also do photography and may soon adopt Git as a platform to share those projects as well. There will also be the occasional pixel art upload from me. I tend to work in sporadic bursts because frankly my work ethic is atrocious. In an attempt to fix this, I'll be logging 300 words a day to MUDDLE as of today. 

I'm pulling out from social media so if you want to reach me it'd be best to do so through my email (ask me for this) or through Discord: sadlad#4391. I do look forward to playing in the sandbox with you all. c:

**Comment by gmoe** [comment]
Howdy, my name is Griffin! I'm a recent software engineering grad and I currently work in the industry as a UX Engineer. I got my start in DH doing [commissioned work](http://griffinmoe.com/coding/michalak/2013/05/14/michalak-project.html) for Loyola University Chicago's Center for Textual Studies and Digital Humanities, and found my home here when I realized there were more passionate technical people doing cool projects than in my own major 😝.

My primary focus is in audio and music, and a lot of my personal projects have DH overlap. A good example is my [emulation of early speech synthesis](http://griffinmoe.com/voder/) called the VODER, which I made to give visitors an understanding of what Helen Harper was capable of at the machine. Usually I'm not that artistically talented, the visual design is based on one of the [pamphlets](https://i1.wp.com/120years.net/wordpress/wp-content/uploads/VODER-Worlds-Fair-Pamphlet.jpeg) they handed out at the World's Fair. So no I didn't design that cool art deco logo, I just redrew it.

I'm also the co-founder of a laptop ensemble called the [Loyola University Technology Ensemble](https://lute.luc.edu/) which performs around Chicago. We actually played at music festival over the summer with audience member participation, so I can cross that one off my bucket list!

I guess you could say I'm MUDDLE's technical advisor? That also extends to anyone who needs help fulfilling their MUDDLE visions! I'll also be contributing content, maybe offering up some of my orphaned projects that haven't seen the light of day. Maybe even short stories if I can find where they're hiding...at least my code is fairly well organized. Here's a [hint at stuff coming MUDDLE's way](https://codepen.io/anon/pen/VqaZez?editors=0010) soon.

My only social media presence is on Twitter ([@griffin_moe](https://twitter.com/griffin_moe)), and it's the only place I don't get my `gmoe` handle 😩

**Comment by taylorcate** [comment]
Thank you so much @jksily and @gmoe!

**Comment by nadinejl** [comment]
This is so exciting! 

Wonderful to hear more of your story @taylorcate, and to see your artwork on Pathbrite — the flower digital humanities model, and the “lady with flowers" — gorgeous. The latter reminded me of the Vogue art covers. 

@jksily, looking forward to reading your short stories and perhaps seeing some photography! 

@gmoe: the VODER — wow, what a cool project. Loved the revamped logo and the video. Beautiful UX on the site. Tried it out. Addictive for a linguophile!

**Comment by nadinejl** [comment]
Hi everyone! I’m Nadine. I’m from southwestern Canada (Vancouver area, and Sunshine Coast), living with my husband and four boys in the middle of France. 
We’ve also spent two years in Cambridge UK when my husband had a contract there. 

My main creative interests are in art, literature, language, and what I call “bloom synergy” — elevating world consciousness through creative connection. 

My BA from SFU in 1998 was in Linguistics. Music is a side hobby that also brings me great pleasure. 

I got started on Github because:

1) My husband suggested it might a good solution for my obsessive urge to document process, and because of its inherent collaborative possibilities, and 

2) My eldest (now 14-year-old) son is into coding, and thought it would be a fun project. So last fall we made a Github Pages site together, which we sporadically maintained and attempted to improve, and which is how Taylor came into contact with me.

I have no other experience with Git. I only have experience making commits on Github in order to generate web content for my Github Pages sites. In other words, ”command line newbie in the house, yo!”

Besides nadinejl.github.io, I am also at bloomwords.com (WordPress, at the moment), @bloom.words (Instagram) and @bloom_words (Twitter). Email is good, too: njl [at] bloomwords.com.

Great to connect with you all. Looking forward to muddling together!
